Fix AttributeError with VocalWare
options['voice'] for VocalWare is nested dictionary instead of string.
E.g. VocalWare ({'engine_id': 3, 'language_id': 1, 'voice_id': 4})

Fallback to 'unknown' to avoid an exception:

...
File "..../awesometts/router.py", line 467, in substitute
  return options['voice'].lower()
AttributeError: 'dict' object has no attribute 'lower'

It's just a quick fix, file names with different language settings
could override in a corner case.